[package]
name = "trading_test_bot"
version = "0.1.0"
authors = ["Jizba Radek <r.jizba@seznam.cz>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
